export type ConsumerConfigInput = {
  baseUrl: string;
  issuer?: string;
  audience?: string;
  jwksUrl?: string;
};

export type ConsumerConfig = {
  baseUrl: string;
  issuer: string;
  audience: string;
  jwksUrl: string;
};

export type NextSetupOptions = {
  adminPrefix?: string;
  publicPaths?: string[];
};

function normalizePath(path: string): string {
  const trimmed = path.trim();
  if (!trimmed) {
    return "/";
  }

  const withPrefix = trimmed.startsWith("/") ? trimmed : `/${trimmed}`;
  if (withPrefix.length > 1 && withPrefix.endsWith("/")) {
    return withPrefix.replace(/\/+$/, "");
  }

  return withPrefix;
}

export function normalizePublicPaths(value: string | undefined): string[] | undefined {
  if (!value) {
    return undefined;
  }

  const parsed = value
    .split(",")
    .map((entry) => normalizePath(entry))
    .filter((entry) => entry.length > 0);

  if (parsed.length === 0) {
    return undefined;
  }

  return Array.from(new Set(parsed));
}

export function normalizeBaseUrl(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) {
    throw new Error("Base URL is required.");
  }

  let parsed: URL;
  try {
    parsed = new URL(trimmed);
  } catch {
    throw new Error("Base URL must be a valid URL.");
  }

  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw new Error("Base URL must use http or https.");
  }

  return parsed.origin;
}

export function buildConsumerConfig(input: ConsumerConfigInput): ConsumerConfig {
  const baseUrl = normalizeBaseUrl(input.baseUrl);
  const issuer = input.issuer?.trim() || baseUrl;
  const audience = input.audience?.trim() || "way-clients";
  const jwksUrl = input.jwksUrl?.trim() || `${baseUrl}/api/v1/jwks`;

  return {
    baseUrl,
    issuer,
    audience,
    jwksUrl,
  };
}

export function buildEnvFile(config: ConsumerConfig): string {
  return [
    `WAY_AUTH_BASE_URL="${config.baseUrl}"`,
    `WAY_AUTH_ISSUER="${config.issuer}"`,
    `WAY_AUTH_AUDIENCE="${config.audience}"`,
    `WAY_AUTH_JWKS_URL="${config.jwksUrl}"`,
    "",
  ].join("\n");
}

export function mergeEnvFile(existingContent: string, updates: Record<string, string>): string {
  const lines = existingContent === "" ? [] : existingContent.split(/\r?\n/);
  const assignmentIndexes = new Map<string, number>();
  const assignmentPattern = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/;

  lines.forEach((line, index) => {
    const match = assignmentPattern.exec(line);
    if (!match) {
      return;
    }
    assignmentIndexes.set(match[1], index);
  });

  const nextLines = [...lines];
  for (const [key, value] of Object.entries(updates)) {
    const rendered = `${key}="${value}"`;
    const existingIndex = assignmentIndexes.get(key);
    if (existingIndex === undefined) {
      nextLines.push(rendered);
      assignmentIndexes.set(key, nextLines.length - 1);
      continue;
    }

    nextLines[existingIndex] = rendered;
  }

  const merged = nextLines.join("\n").replace(/\n{3,}/g, "\n\n");
  return merged.endsWith("\n") ? merged : `${merged}\n`;
}

function buildMiddlewareConfigBlock(options: NextSetupOptions): string {
  const entries: string[] = [];
  if (options.adminPrefix) {
    entries.push(`adminPrefix: "${normalizePath(options.adminPrefix)}"`);
  }
  if (options.publicPaths && options.publicPaths.length > 0) {
    entries.push(`publicPaths: ${JSON.stringify(options.publicPaths)}`);
  }

  if (entries.length === 0) {
    return "";
  }

  return `  middleware: {\n${entries.map((entry) => `    ${entry},`).join("\n")}\n  },\n`;
}

export function buildNextAuthFile(options: NextSetupOptions = {}): string {
  const middlewareBlock = buildMiddlewareConfigBlock(options);
  const body =
    middlewareBlock.length > 0
      ? `export const auth = createWayAuthNext({\n${middlewareBlock}});\n`
      : "export const auth = createWayAuthNext();\n";

  return [
    'import { createWayAuthNext } from "@way/auth-sdk/next";',
    "",
    "// Generated by way-auth-setup --framework next --minimal",
    body,
    "export const wayAuthMiddleware = auth.middleware;",
    "export const wayAuthMatcher = auth.matcher;",
    "",
  ].join("\n");
}

export function buildNextMiddlewareFile(): string {
  return [
    'import { wayAuthMatcher, wayAuthMiddleware } from "./src/lib/auth";',
    "",
    "export default wayAuthMiddleware;",
    "",
    "export const config = {",
    "  matcher: wayAuthMatcher,",
    "};",
    "",
  ].join("\n");
}

export function buildNextEnvUpdates(baseUrl: string): Record<string, string> {
  return {
    WAY_AUTH_BASE_URL: normalizeBaseUrl(baseUrl),
  };
}

export function buildSetupGuide(config: ConsumerConfig): string {
  return `# WAY Auth Service Consumer Setup\n\nThis guide was generated by \`way-auth-setup\` for the WAY Auth Service.\n\n## Environment Variables\n\nAdd these to your app's environment (example below is for .env.local):\n\n\`\`\`bash\nWAY_AUTH_BASE_URL="${config.baseUrl}"\nWAY_AUTH_ISSUER="${config.issuer}"\nWAY_AUTH_AUDIENCE="${config.audience}"\nWAY_AUTH_JWKS_URL="${config.jwksUrl}"\n\`\`\`\n\n## Client Usage (Browser / React)\n\n\`\`\`ts\nimport { createWayAuthClient } from "@way/auth-sdk/client";\n\nconst auth = createWayAuthClient({\n  baseUrl: process.env.WAY_AUTH_BASE_URL!,\n  credentials: "include",\n});\n\nawait auth.login({ email: "demo@example.com", password: "password" });\nconst me = await auth.me();\n\`\`\`\n\n## Server Usage (JWT Verification)\n\n\`\`\`ts\nimport { createWayAuthGuard } from "@way/auth-sdk/server";\n\nconst guard = createWayAuthGuard({\n  jwksUrl: process.env.WAY_AUTH_JWKS_URL!,\n  issuer: process.env.WAY_AUTH_ISSUER!,\n  audience: process.env.WAY_AUTH_AUDIENCE!,\n});\n\`\`\`\n`;
}

export function buildNextSetupGuide(input: {
  baseUrl: string;
  envPath: string;
  authFilePath: string;
  middlewarePath: string;
}): string {
  return `# WAY Auth Next.js Setup\n\n## Fastest Next.js setup\n\n1. Install SDK:\n\n\`\`\`bash\nbun add @way/auth-sdk\n\`\`\`\n\n2. Run setup:\n\n\`\`\`bash\nbunx way-auth-setup --framework next --minimal\n\`\`\`\n\n3. Ensure this env key exists in \`${input.envPath}\`:\n\n\`\`\`bash\nWAY_AUTH_BASE_URL="${input.baseUrl}"\n\`\`\`\n\nNo additional WAY Auth env vars are required for baseline Next.js integration.\n\n## What was generated\n\n1. \`${input.authFilePath}\`\n- Creates \`createWayAuthNext()\` singleton.\n- Exports middleware and matcher bindings.\n\n2. \`${input.middlewarePath}\`\n- Re-exports SDK middleware and matcher.\n\n3. \`${input.envPath}\`\n- Merged/updated with \`WAY_AUTH_BASE_URL\`.\n\n## Runtime mental model\n\n1. Middleware checks protected admin routes.\n2. Client methods (\`auth.client.*\`) manage login/signup/logout/bootstrap.\n3. Server helpers (\`auth.server.*\`) validate session from access-token cookie.\n4. SDK resolves issuer/audience/JWKS/endpoints using discovery at:\n- \`/.well-known/way-auth-configuration\`\n\n## Usage snippets\n\n### Client login\n\n\`\`\`ts\nimport { auth } from "@/lib/auth";\n\nawait auth.client.login({ email: "demo@example.com", password: "password" });\n\`\`\`\n\n### Client bootstrap\n\n\`\`\`ts\nconst result = await auth.client.bootstrapSession();\nif (!result.ok) {\n  console.log(result.error.message);\n}\n\`\`\`\n\n### Server session\n\n\`\`\`ts\nimport { auth } from "@/lib/auth";\n\nconst session = await auth.server.getSession(request);\n\`\`\`\n\n## Troubleshooting\n\n1. Redirect loops on admin routes:\n- Confirm \`middleware.ts\` exports SDK middleware.\n- Confirm access token cookie is not blocked by browser policy.\n\n2. Discovery/config errors:\n- Verify \`${input.baseUrl}/.well-known/way-auth-configuration\` is reachable.\n\n3. Session returns null server-side:\n- User may be logged out, token expired, or cookie not present.\n\n## Migration notes (from custom wrappers)\n\n1. Delete custom auth config/constants/client/server wrapper files.\n2. Replace middleware logic with generated \`middleware.ts\`.\n3. Replace direct client wrapper calls with \`auth.client.*\`.\n4. Replace server wrapper calls with \`auth.server.getSession/requireSession\`.\n`;
}
