export type ConsumerConfigInput = {
  baseUrl: string;
  issuer?: string;
  audience?: string;
  jwksUrl?: string;
};

export type ConsumerConfig = {
  baseUrl: string;
  issuer: string;
  audience: string;
  jwksUrl: string;
};

export function normalizeBaseUrl(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) {
    throw new Error("Base URL is required.");
  }

  let parsed: URL;
  try {
    parsed = new URL(trimmed);
  } catch {
    throw new Error("Base URL must be a valid URL.");
  }

  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw new Error("Base URL must use http or https.");
  }

  return parsed.origin;
}

export function buildConsumerConfig(input: ConsumerConfigInput): ConsumerConfig {
  const baseUrl = normalizeBaseUrl(input.baseUrl);
  const issuer = input.issuer?.trim() || baseUrl;
  const audience = input.audience?.trim() || "way-clients";
  const jwksUrl = input.jwksUrl?.trim() || `${baseUrl}/api/v1/jwks`;

  return {
    baseUrl,
    issuer,
    audience,
    jwksUrl,
  };
}

export function buildEnvFile(config: ConsumerConfig): string {
  return [
    `WAY_AUTH_BASE_URL=\"${config.baseUrl}\"`,
    `WAY_AUTH_ISSUER=\"${config.issuer}\"`,
    `WAY_AUTH_AUDIENCE=\"${config.audience}\"`,
    `WAY_AUTH_JWKS_URL=\"${config.jwksUrl}\"`,
    "",
  ].join("\n");
}

export function buildSetupGuide(config: ConsumerConfig): string {
  return `# WAY Auth Service Consumer Setup\n\nThis guide was generated by \`way-auth-setup\` for the WAY Auth Service.\n\n## Environment Variables\n\nAdd these to your app's environment (example below is for .env.local):\n\n\`\`\`bash\nWAY_AUTH_BASE_URL=\"${config.baseUrl}\"\nWAY_AUTH_ISSUER=\"${config.issuer}\"\nWAY_AUTH_AUDIENCE=\"${config.audience}\"\nWAY_AUTH_JWKS_URL=\"${config.jwksUrl}\"\n\`\`\`\n\n## Client Usage (Browser / React)\n\n\`\`\`ts\nimport { createWayAuthClient } from \"@way/auth-sdk/client\";\n\nconst auth = createWayAuthClient({\n  baseUrl: process.env.WAY_AUTH_BASE_URL!,\n  credentials: \"include\",\n});\n\nawait auth.login({ email: \"demo@example.com\", password: \"password\" });\nconst me = await auth.me();\n\`\`\`\n\n## Signup with Password Confirmation\n\n\`\`\`ts\nimport { createWayAuthState } from \"@way/auth-sdk/state\";\n\nconst state = createWayAuthState(auth);\nawait state.signupWithConfirm({\n  email: \"demo@example.com\",\n  password: \"password\",\n  confirmPassword: \"password\",\n});\n\`\`\`\n\n## React Callbacks\n\n\`\`\`tsx\nimport { useWayAuthCallbacks, useCreateWayAuthState } from \"@way/auth-sdk/react\";\n\nconst controller = useCreateWayAuthState(auth);\nuseWayAuthCallbacks(controller, {\n  onLoginSuccess: (_state, user) => {\n    console.log(\"Signed in\", user.email);\n  },\n  onSignupSuccess: (_state, user) => {\n    console.log(\"Signed up\", user.email);\n  },\n});\n\`\`\`\n\n## Error Map Helper\n\n\`\`\`ts\nimport { getWayAuthErrorMessage } from \"@way/auth-sdk\";\n\ntry {\n  await auth.login({ email: \"demo@example.com\", password: \"bad\" });\n} catch (error) {\n  console.log(getWayAuthErrorMessage(error));\n}\n\`\`\`\n\n## Server Usage (JWT Verification)\n\n\`\`\`ts\nimport { createWayAuthGuard } from \"@way/auth-sdk/server\";\n\nconst guard = createWayAuthGuard({\n  jwksUrl: process.env.WAY_AUTH_JWKS_URL!,\n  issuer: process.env.WAY_AUTH_ISSUER!,\n  audience: process.env.WAY_AUTH_AUDIENCE!,\n});\n\`\`\`\n\n## CORS (Important)\n\nIf your frontend runs on a different origin than the auth service, ask the auth service admin to add your origin in the admin CORS UI.\n\n- Example origin: \`http://localhost:5174\`\n\n## Notes\n\n- Access tokens are short-lived and should be stored in memory.\n- Refresh tokens are stored in HttpOnly cookies managed by the auth service.\n- \`fetchWithAuth\` retries once on 401 by calling \`refresh()\`.\n`;
}
